on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-scan:
    name: Container Scan
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-container-scan.yml@feat/grype-scan
    with:
      runtime: python
